version: '3'
services:
  my_component:
    # Here you can specify an env-file with variables
    # that can be used in the docker-container,
    # BUT these variables can not be used here in the
    # docker-compose using ${...} UNLESS it is a file named
    # ".env". This file (in the same directory) is always
    # loaded into the docker-compose, but not into the 
    # docker-containers unless the variables are mapped in the 
    # environment option below or using the env_file option here.
    env_file: .env
    container_name: homeServerIpUpdates
    build:
      context: .
      dockerfile: Dockerfile
    environment: # specify the env-variables here
      # secret ones in .env file or system
      #TELEGRAM_BOT_TOKEN: ${MY_SECRET_VARIABLE}
      #TELEGRAM_CHAT_ID: ${MY_SECRET_VARIABLE}
      # and public ones can be hardcoded
      #MY_PUBLIC_VARIABLE: Hello world
      # sometimes the console won't show print messages,
      # using PYTHONUNBUFFERED: 1 can fix this
      PYTHONUNBUFFERED: 1